---
- name: Setup Docker
  hosts: rpiservers
  remote_user: pi

  tasks:
  - name: Create deploy directory
    file:
      path: /home/pi/deploy
      state: directory
  - name: Copy mqtt_sender items
    copy: 
      src: "{{ item.src }}" 
      dest: /home/pi/deploy
      owner: pi
      group: pi
      mode: "{{ item.mode | default('444') }}"
    loop:
      - src: ../../src/bin/mqtt_sender
        mode: '774'
      - src: ../../src/scripts
      - src: ../../src/systemd
      - src: ../../src/sensors
      - src: ../../src/config.yml
  - name: Copy systemd services
    become: true
    copy: 
      remote_src: true
      src: /home/pi/deploy/systemd/system/
      dest: /etc/systemd/system/
  - name: Enable get-temperature service
    systemd:
      name: get-temperature
      enabled: true
      state: started
  - name: Enable publish-temperature service
    systemd:
      name: publish-temperature
      enabled: true
      state: started
