name: Dependencies
on:
  schedule:
    # - cron:  '0 17 1 1-12 *'
    - cron:  '22 9 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.0.2
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: renovate.json
          renovate-version: 37.172.2
